title: Kyle Harrison # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
   👋 I am aspiring Data Analyst who loves Baseball ⚾ <br><br>
  [LinkedIn](www.linkedin.com/in/kyle-harrison-data-analytics) 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
